### ISSUE TITLE
[Suggestion] Bar Texture update?

### ISSUE THREAD

**Issue by Z-Tunic** [Tfarcenim/ClassicBar#10]
If you don't mind, I did a edit to the textures and was wondering on how it looked.

![](https://cdn.discordapp.com/attachments/377171551155650560/562289265677959168/classicbarupdatedtexture.PNG)

The dimensions are still the same so I thought no issues would appear but apparently due to the way the bar filling render works the bars on the right are off by 1 pixel, except... for the food bar for some reason. Absorption bar also appears to be off by 1 pixel if it isn't at 20. Health Bar border flashes on the outer part inside of the gray border when taking damage much like how the hearts do.

Here's what the texture looks like. I didn't touch the exhaustion as I kinda liked how it overlaps the actual bar & border. The Shield Icon is left untouched as well.
![](https://cdn.discordapp.com/attachments/377171551155650560/562289296812539908/health.png)

P.S.
Don't suppose the Armor & Toughness colors could be changed slightly? They kinda blend in with the grey border even with the default textures.

**Comment by Tfarcenim** [comment]
Taken into consideration, will implement soon once I work out the bugs.

**Comment by Z-Tunic** [comment]
I forgot to mention that for some reason the Food Bar darkens slightly if you have Armor/Toughness Bars... maybe one of them. Not sure why that occurs but maybe it happens with the default textures but you perhaps won't notice it.

**Comment by Tfarcenim** [comment]
Hmm, I think it has to do with rendering order, I'll see if I can fix that.

**Comment by Tfarcenim** [comment]
It's done
