### ISSUE TITLE
Hope to be compatible with Inventory HUD+

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/ClassicBar#105]
Hope to be compatible with Inventory HUD+
![QQ截图20230112142535](https://user-images.githubusercontent.com/83486178/211994365-df20ea59-615a-4f9a-aac4-1eeada0d8eec.png)

**Comment by Tfarcenim** [comment]
I don't get it, what am I supposed to do?

**Comment by ghost** [comment]
> 我不明白，我该怎么办？

Sorry for forgetting to explain, the fonts overlap, hope it can be compatible.

**Comment by ghost** [comment]
Fonts overlap, hope the mod is compatible.

**Comment by ghost** [comment]
Can you make the text appear inside the blood bar?

**Comment by Tfarcenim** [comment]
I don't think there's anything I can do on my end
