### ISSUE TITLE
[Bug] Compatibility with mods

### ISSUE THREAD

**Issue by adsioho** [Tfarcenim/ClassicBar#126]
When used with MUI, numbers are not rendered when the health bar is yellow
![image](https://github.com/Tfarcenim/ClassicBar/assets/116698397/ae0a30c3-c329-4887-b624-198ecbe0226c)

**Comment by adsioho** [comment]
Why aren't the numbers rendered?

**Comment by Tfarcenim** [comment]
what is mui

**Comment by adsioho** [comment]
Modern UI

> what is mui

**Comment by adsioho** [comment]
Not an issue with the mod

**Comment by adsioho** [comment]
Not an issue with this mod
