### ISSUE TITLE
[Bug] Color interpolation calculation is incorrect

### ISSUE THREAD

**Issue by BloCamLimb** [Tfarcenim/ClassicBar#127]
#### Description

Someone reported an issue to my work, see https://github.com/BloCamLimb/ModernUI/issues/207 and https://github.com/Tfarcenim/ClassicBar/issues/126. After reviewing your code, I found out why.

https://github.com/Tfarcenim/ClassicBar/blob/3af10ed211803cec582f674015fc67a490abf0db/src/main/java/tfar/classicbar/util/ColorUtils.java#L49-L53

Inverse of linear interpolation should be `(v - low) / (high - low)`, and you wrote `v - low / (high - low)`, causing the R,G,B components of the color to be out of the range of 0-255.

https://github.com/Tfarcenim/ClassicBar/blob/3af10ed211803cec582f674015fc67a490abf0db/src/main/java/tfar/classicbar/util/Color.java#L34-L36

Then R and G are left shifted to alpha component (here you should use bitwise OR '|' instead of plus '+'). I tested with your default config values, and the result colors are something like 0x027dff00, where alpha is always 2. This is a nearly transparent color, and it should be discarded in alpha test.

#### Minimum reproducible code
```java
public static double mix(double a, double b, double t) {
    return a * (1 - t) + b * t;
}
public static int wrong(int c1, int c2, double v, double lo, double hi) {
    double f = v - lo / (hi - lo); // your code is wrong here
    int r = (int) Math.floor(mix(c1 >> 16 & 0xFF, c2 >> 16 & 0xFF, f));
    int g = (int) Math.floor(mix(c1 >> 8 & 0xFF, c2 >> 8 & 0xFF, f));
    int b = (int) Math.floor(mix(c1 & 0xFF, c2 & 0xFF, f));
    return (r << 16) + (g << 8) + b; // plus is okay, but OR is faster
}
public static void main(String[] args) {
    for (double i = 0.5; i < 0.75; i += 0.01) {
        System.out.println(Integer.toHexString(wrong(0xFFFF00, 0x00FF00, i, 0.5, 0.75)));
    }
}
```

#### So why wouldn't this issue appear in Vanilla?

The  alpha threshold in Vanilla is 4 (see Font class), which means that if alpha is less than 4, it will automatically be set to 255 (opaque color). In this way, Font can be compatible with colors in both AARRGGBB and RRGGBB formats. The threshold value for alpha test in shader is 0.1, which is equal to 25 in the range of 0-255. This means that in vanilla, a text with an alpha value of 4-25 will not render, 0-3 and 26-255 will render.

However, the alpha threshold in Modern UI is 2, see ModernTextRenderer class. The threshold value for alpha test in shader is 0.01, which is equal to 2 in the range of 0-255; This means that only when the alpha value is 2, the text will not render, and having other alpha values will render. And your incorrect alpha result happens to be 2. 

#### Solution
Use Minecraft's `Mth.inverseLerp(v, low, high)`

**Comment by Tfarcenim** [comment]
Thank you, this has been fixed in dev
