### ISSUE TITLE
Graphical Glitches: Hunger Offset & Armor Flashing

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#13]
![image](https://user-images.githubusercontent.com/36409872/55676230-9175bc00-589e-11e9-9c8a-7babcb806235.png)
Hunger restored overlay seems to render a pixel too many to the left. It also appeared to affect saturation at a similar threshold to when the hunger bar itself glitches out, but I haven't been able to replicate that last part with the saturation lately with [v1.11].

Total affected range appears to be 10 to 16 hunger, theoretically the same for saturation, but haven't been able to replicate yet.
The clip shows 16hunger 0saturation having this desync.

**Comment by Khioni** [comment]
![image](https://user-images.githubusercontent.com/36409872/55676103-aac93900-589b-11e9-88ae-f89e397669e0.png)
Also, the transparent armor bar glitch still happens with the "low durability effect", and I doubt it's intentional that the _armor_ bar flashes for an _hand-equipped_ item.

**Comment by Tfarcenim** [comment]
ok, that is stupid, I'll fix it to only flash for armor items

**Comment by Khioni** [comment]
To clarify the armor glitch: **I've easily replicated not only the overlay triggering with all items, but when offending items are removed, the opacity stays the same, which at the right time, can make the armor bar unreadable asides from the number.**

**Comment by Tfarcenim** [comment]
Should be fixed in 0.1.12

**Comment by Khioni** [comment]
**Can definitely confirm that both glitches are fixed.**
