### ISSUE TITLE
Baubles API LavaCharm Crash

### ISSUE THREAD

**Issue by FriendlyGamer** [Tfarcenim/ClassicBar#14]
Hi from further inspection I suspect that ClassicBars is the issue out of the two in the crash suspects. updated both my server and client and I crashed upon joining my newly updated server.   

Here is the crash log https://paste.dimdev.org/idagiqogop.mccrash 

If BetterHUD has to do with it instead/alongside just let me know and I will refer them to this.

**Comment by Tfarcenim** [comment]
I see the issue here, right now the lava bar HUD only works if randomthings is installed, the next update should resolve this

**Comment by FriendlyGamer** [comment]
> I see the issue here, right now the lava bar HUD only works if randomthings is installed, the next update should resolve this

Ahh I see, so this was new due to Random Things not being as regular as Vanilla/other mods combos?

**Comment by Tfarcenim** [comment]
Yes, I need to do a seperate handler for the case of Random things and no baubles

**Comment by Tfarcenim** [comment]
Game crashes because it classloads imports from baubles which don't exist in the modpack.

**Comment by Tfarcenim** [comment]
fixed in 0.1.12 there is now a handler for it.
