### ISSUE TITLE
[Enhancements] Some effect-related things

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#16]
- Taking damage cuts to the current HP, with no indication of exactly how much damage was done.
  - For default reference, unless the active texturepack gets rid of them by editing the icons file, the default hearts have a flashing overlay that shows how much damage the last hit took.
  - A concept sketch of how it could look on the new HP bar here is below.
- Other than the configurable colors, the HP bar has no real effect for low HP.
  - For default reference, MC jitters the hearts at <=4HP.
  - I could see the HP bar flashing like the armor bar when a piece is about to break, or using custom, default-type shaking, with a configurable threshold (default 20%).
  - Wither forces it to turn purely grayscale as it is right now, which can look awkward with certain texturepacks that don't use default-style black hearts, since Classic Bars supports texturepacks, pulling icons from their assets.
    - Considering that people can already make texturepacks to change the wither hearts to something more visible, I believe it would be fair to allow the wither effect colors to be changed.
    - Poison could force the bar to a sickly green, also configurable to better fit texturepacks, and/or add a bubbly effect to the bar itself as I have seen mentioned before in other enhancement posts, with my concept design below the sketch of the flashing HP.
- Like with HP, hunger has no noticable effect when it's low.
  - For default reference, hunger usually jitters when there's no saturation, getting worse as it drops lower.
  - It could flash when at the no-sprint threshold (usually 6) or lower, and optionally mimic default MC jitter.
- Speaking of armor about to break: It would be amazing were it possible to make it only flash the defense that will be lost soon from the armor pieces that are about to break.

![concept](https://user-images.githubusercontent.com/36409872/56431682-a5ef8680-6298-11e9-8105-b3c79bbf9f12.png)
(Damage flash overlay concept. Damage = White here, but you do you.)

![concept2](https://user-images.githubusercontent.com/36409872/56433964-be639f00-62a0-11e9-84bb-685558a97307.png)
(Poison overlay concept: A clear bubbly texture with no specific color, that optionally could change the HP bar color. If it were to not recolor it, then it would obey the normal HP colors.)

**Comment by Tfarcenim** [comment]
taking it one step at a time

Armor fixed in 0.1.14 (sort of)

**Comment by Tfarcenim** [comment]
0.1.15 added the interpolation.

**Comment by Tfarcenim** [comment]
0.1.16 - Added poison overlay
- Added low health warning.

last things will be configurable wither overlay and poison overlay but hose will likely be a mess because of the scaling.

**Comment by Tfarcenim** [comment]
Alright, 0.2.0 fixes the last of these issues meaning this is resolved.

**Comment by Khioni** [comment]
(LOL, the convinience link-reference reopened it!)
I mentioned an addendum, so when things are fixed up again, maybe this could be considered.
- Wither could make the bar use a different texture with flatter shading.
