### ISSUE TITLE
[Graphical Glitches] Botania: Flight Boost cooldown doesn't render

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#17]
![image](https://user-images.githubusercontent.com/36409872/56463372-d3bff280-63a0-11e9-977c-7e03e52a200f.png)
Temporary fix for user: Set both heights to -2 in the config. However, this gets also rid of the bar for the boost cooldown. Setting to 0 keeps the bar, but rendering inside the bottom of the hotbar.

**Comment by Tfarcenim** [comment]
Have you tried setting both in the config to 1000?

**Comment by Khioni** [comment]
Either 1000 or -2 does work, but regardless, **the dash cooldown bar won't be there either**

**Comment by Tfarcenim** [comment]
Aaargh, which gadget adds the dash

**Comment by Khioni** [comment]
The dash is built into the crown itself. LCTRL/SPRINT while flying forwards triggers it.

**Comment by Tfarcenim** [comment]
Thank you I will have that issue fixed

**Comment by Khioni** [comment]
Can definitely confirm it's fixed on my end.
