### ISSUE TITLE
[Offset Error] Disabled toughness bar makes Botania fly bar float

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#18]
Only happens when one has armor toughness, with the config for that to show up disabled.
![2019-04-24_15 31 45](https://user-images.githubusercontent.com/36409872/56688298-5816bc00-66a6-11e9-98ae-076b1b81ad78.png)

**Comment by Tfarcenim** [comment]
resolved in 0.1.16a
