### ISSUE TITLE
[Graphics-Bug]Wither & Poison using wrong colors

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#19]
- Versions
  - MC: 1.12.2
    - Forge: 14.23.5.2836
    - Classic Bars: 0.2.0

- Glitches
![image](https://user-images.githubusercontent.com/36409872/56970882-1bc7dd80-6b36-11e9-9f5a-ed5473fb0b11.png)
Poison is almost fine, but the normal HP colors seem to override poison's colors at the highest threshold.
![image](https://user-images.githubusercontent.com/36409872/56971098-9690f880-6b36-11e9-93e6-9ee8abb69794.png)
![image](https://user-images.githubusercontent.com/36409872/56971114-a27cba80-6b36-11e9-9f86-ecd874901e45.png)
Wither is especially glitchy, using poison colors for the bar, but correctly using wither colors for the numbers, when below the highest HP threshold (once again with highest normal HP threshold completely overriding the status's)

When both statuses are active, the overlays work as default: poison overrides wither, which is fine as-is, so no issue there.

- Colors/Thresholds used
  - Normal: FF0033 (0.25), FFFF00 (0.5), 00FF33 (0.75)
  - Poison: 009933 (0.25), 00CC66 (0.5), 00FF66 (0.75)
  - Wither: 990099 (0.25), CC00CC (0.5), FF00FF (0.75)

**Comment by SirAron111** [comment]
I can confirm this happening colors don’t change and wither doesn’t display any effect overlay like poison does.  As well as both keeping the standard color of the HP bar (green) until the very end.

**Comment by Khioni** [comment]
In case of Wither + Poison stacked at the same time, it does obey default Minecraft display rules (poison overrides wither), which is fine as-is.

> wither doesn’t display any effect overlay like poison does

Back in my enhancement block with effect-related things, I hadn't mentioned any special overlay for wither, just the colors, so I wouldn't say that part is a bug, but maybe that could be an addendum to my earlier block of text with enhancements.

@SirAron111 - Config lines used when they glitched out with to apparently show the normal green until the very end?

**Comment by Khioni** [comment]
Speaking of wither effect not having any overlay:
![concept3](https://user-images.githubusercontent.com/36409872/57027837-7aab5680-6c0b-11e9-9c58-141bfd018686.png)
Even default MC doesn't render both poison _and_ wither, so if this could be pulled off, then it would be absolutely amazing.

**Comment by SirAron111** [comment]
Well you see the little green bubbles on the poison it would be nice if there were like little black bone crosses or so for wither. Or little flames when on fire. But the color underneath should just be the default one going from green to red. The problem atm is that the color stays green all the way until you die. Not changing anymore at all.

**Comment by Khioni** [comment]
> it would be nice if there were like little black bone crosses or so for wither.

Admittedly, I was aiming for a Faithful-y one, since they just turn the hearts black with a very dark red outline for wither. Having a more simple wither overlay would make it so that both it and the poison effects can stack without the bar becoming a mess of multiple different overlays.

The resolution of the bars (going by the updated spritesheet, not the classic one) is definitely smaller than my paint sketches, so it unfortunately might not even be able to fit _and_ look good at the same time.

On top of that, it might be tricky to get the blackened bone crosses to stack _and_ look good with the poison effect, unless we just fall back to default MC behavior with poison completely overriding it.

> Or little flames when on fire.

Frankly, fire already covers the screen as it is in default MC. But then again, there could always be configs to toggle overlays individually.

> The problem atm is that the color stays green all the way until you die. Not changing anymore at all.

It's odd that you seem to be getting "green all the way until you die" no matter what, 'cause on my screen, it does use the colors like usual, it's just the Poison and Wither that are bugged with the top threshold glitching out to normal life colors. Have you double-checked the config to make sure nothing's corrupted?

**Comment by Tfarcenim** [comment]
0.3.0 should resolve most of these.

**Comment by Khioni** [comment]
Can confirm the colors being fixed on my end.

**Comment by SirAron111** [comment]
yep fixed it works great now

**Comment by SirAron111** [comment]
Love your mod support its one of the best there is.

**Comment by Khioni** [comment]
Closing as we've been able to confirm the colors being fixed, and I X-Posted the wither overlay to #21.
