### ISSUE TITLE
[Annoyance] Food Poison makes it nigh-impossible to see

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#22]
![image](https://user-images.githubusercontent.com/36409872/57144723-ae16ee00-6d8f-11e9-85cd-ae82a61f7bfb.png)
To be honest, it's really hard to see the new, **very dark** green when food poisoned against the dark background. On top of that, saturation is unaffected, staying as the color set in config.

- Since life poison colors are already configurable, the food poison should also be configurable. Default poison has reasonable defaults, so the current default food poison color could be brighter so they're easily visible against the dark background out-of-box.
- Logically, since life poison has the bubbles overlay, food poison should use the same overlay, except placed on the hunger bar.

**Comment by Tfarcenim** [comment]
hardcoding it was a bad idea, I'll have that fixed

**Comment by Khioni** [comment]
While the main point (_that it used to be nigh-impossible to see the food poison bar_) is definitely fixed, the whole thing is only about half-fixed.

## Recap
#### CONFIRMED TO BE FIXED
- Food poison default is certainly reasonable now
- Config works perfectly fine
#### STILL UNIMPLEMENTED
- Saturation still unaffected
- Optional, and admittedly perfectionism: Also use the bubble overlay from life poison, except on the hunger bar.

**Comment by Tfarcenim** [comment]
# 1 is going to be implemented in 0.3.2, the other is not because it's a pain in the ass.

**Comment by Khioni** [comment]
Assuming it's the **poison saturation color** that would be such a pain, I'd be perfectly fine with simply stacking the life poison overlay, as either way, it'd make it more visible.

**Comment by Khioni** [comment]
Closing as pretty much everything is solved, and the extra overlay to match it up with HP status can be revisited later on.
