### ISSUE TITLE
[Enhancement] Critical Flashing Behavior & Consistency

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#23]
## Thresholds
- Configurable by % (tick-based, like Air and Botania Fly, or scaling, like Life) or precise values (normally fixed caps, like Hunger)
- Certain mod bars (lava charm, flying) could have these set, too.
## Graphics
- For consistency, all bars should either use the blinking (currently used for Life and Hunger) or fading (currently used for near-broken Armor)
- If it is possible to make fading work for the other bars, a config to flip between these two styles

**Comment by Khioni** [comment]
I noticed that in 0.3.2, the following have been implemented:
- HP Threshold configgable
- All bars use blinking now

I feel like hunger should be another configgable one, since some (such as myself) may prefer it to be at 6 points instead, making the flashing threshold when it usually disables sprinting.

I understand if it's a pain to make smooth fading work for all bars, and/or to add in the flashing for every new bar that could potentially use it, though.

**Comment by Tfarcenim** [comment]
sorted in 0.3.3
