### ISSUE TITLE
[Glitch] Many graphical glitches in 0.3.2a

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#25]
![image](https://user-images.githubusercontent.com/36409872/58348967-08a3e700-7e30-11e9-8670-dc876f029316.png)
(With % numbers on)

![image](https://user-images.githubusercontent.com/36409872/58349097-60dae900-7e30-11e9-9419-7b4fb21d254f.png)
(With normal point/second numbers)

0.3.2a seems to have broken:
- Tick-based bars (renders an UI pixel too much to the right)
- Hunger (gets stuck just like the old breaking armor fading used to)

Unsure how long it has been there:
- % based numbers occasionally have awkward offset, causing overlapping.

Last known good version on my end was 0.3.2 (haven't really used the % numbers much, so I'm not sure how long that error has been slipping past us)

**Comment by Khioni** [comment]
![image](https://user-images.githubusercontent.com/36409872/58357799-401f8d00-7e4a-11e9-92ce-c3cf12d1970b.png)
Also affects mount life

**Comment by Khioni** [comment]
![image](https://user-images.githubusercontent.com/36409872/58382706-92bc8e80-7f9b-11e9-9b92-3a2c2560ea88.png)
(%)
![image](https://user-images.githubusercontent.com/36409872/58382739-d911ed80-7f9b-11e9-8af4-f81a36576a6f.png)
(%, Mounted)

![image](https://user-images.githubusercontent.com/36409872/58382687-4a04d580-7f9b-11e9-8d9e-ac16eb687538.png)
(Standard)
![image](https://user-images.githubusercontent.com/36409872/58382743-eb8c2700-7f9b-11e9-9637-5bd0a4e4f93f.png)
(Standard, Mounted)

While I can confirm that the % number glitchiness is fixed, and the bars are no longer glitched, 0.3.2a still has the frozen hunger glitch. It _does_ need good timing to replicate, as you'd have to time it so it registers the food being eaten when the bar is flashed out.

**Comment by Tfarcenim** [comment]
0.3.2c should resolve this

**Comment by Khioni** [comment]
Unable to replicate the remaining "stuck hunger" glitch since 0.3.2c, and everything else had also been fixed.
