### ISSUE TITLE
[Error] Armor blinking renders an UI pixel too stretched in both directions

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#26]
![image](https://user-images.githubusercontent.com/36409872/59803007-3c035580-92b8-11e9-8311-598d8d00e070.png)
(Only chain leggings, almost broken)

![image](https://user-images.githubusercontent.com/36409872/59803033-53424300-92b8-11e9-9685-bc0271ef9f85.png)
(Full suit of diamond, with boots almost broken)

**Comment by Tfarcenim** [comment]
mostly resolved on 0.3.4, still have to handle > 20 armor values

**Comment by Khioni** [comment]
![image](https://user-images.githubusercontent.com/36409872/59970244-fd2b0500-952e-11e9-9588-b777a295f751.png)
Debug feature left in? Barely chipped diamond armor already shows the flashing.

**Comment by Tfarcenim** [comment]
working on making it work for all armor levels instead of <=20, will be fixed next update

**Comment by Tfarcenim** [comment]
now fixed in 0.3.4b
