### ISSUE TITLE
[Error] Threshold matches "less than" instead of "less than or equal"

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#27]
i.e If you have **exactly** 4HP, the 0.2 HP threshold doesn't start flashing, effectively making the 20% threshold more like 19.99%, and 30% more like 29.99%.

It became more noticable with hunger since 0.3 should match ≤6 out of 20max, but only matches <6, leading to it not flashing at no-sprint threshold, but anything _below_ it.

- Replication (under default configs: 0.2 HP Critical, 0.3 Hunger Critical):
  - For HP: Make sure you have a perfect 20HP, then with natural regen off or too little hunger to heal from it, admin in poison or wither effect so it drops you to 4. If overshot to <4, admin in regen to get exactly 4HP from there.
  - For Hunger: Admin in a very strong hunger debuff i.e `/effect @p minecraft:hunger 10 255` to quickly drop your hunger to 6. If overshot to <6, eat clownfish until it's exactly 6.

**Comment by Tfarcenim** [comment]
resolved in 0.3.4
