### ISSUE TITLE
Increasing hunger cap breaks the hunger bar.

### ISSUE THREAD

**Issue by Warrock3280** [Tfarcenim/ClassicBar#28]
![2019-06-20_22 19 52](https://user-images.githubusercontent.com/30724185/59860733-ab0ca700-93a9-11e9-8872-637179bc3b9d.png)
![2019-06-20_22 20 38](https://user-images.githubusercontent.com/30724185/59860776-bcee4a00-93a9-11e9-9350-8b5fbf1f0914.png)

**Comment by Tfarcenim** [comment]
Which mod is allowing you to do this?

**Comment by Warrock3280** [comment]
@Tfarcenim 
[**Iblis**](https://minecraft.curseforge.com/projects/iblis)
Gluttony attribute increases hunger cap.

**Comment by Khioni** [comment]
I also see a second glitch in the screencap, and thought I'd bring it to attention, just in case it ends up slipping past: **the lava charm bar being offset down-right by an UI pixel.**

**Comment by Tfarcenim** [comment]
both resolved in 0.3.4
