### ISSUE TITLE
[Error] Damage interpolation renders a pixel stretched to left

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#29]
![image](https://user-images.githubusercontent.com/36409872/59970279-e933d300-952f-11e9-8937-211d4a308dda.png)
(Direct clip)
![image](https://user-images.githubusercontent.com/36409872/59970304-9c043100-9530-11e9-8c81-8293e8418ecb.png)
(Enhanced with Auto Levels)

Replication:
`/kill @p`
If it's hard to notice, take a screenshot right as it kills you, and put it into an image editor. It may be a little hard to see due to the red screen from death, and the white blending in with the frame.

It never appears to happen a pixel to the right under normal conditions, only to the left.
This doesn't seem to be a problem with normal HP, but mortal damage shows the clipping/stretching glitch.

**Comment by Tfarcenim** [comment]
sorted
