### ISSUE TITLE
[Error] Absorption stacked desync

### ISSUE THREAD

**Issue by Khioni** [Tfarcenim/ClassicBar#30]
![image](https://user-images.githubusercontent.com/36409872/59970584-1e442380-9538-11e9-9cfc-102d7e4b7c5b.png)
This config only goes up to 3 layers.

- `FFFF00` [Yellow / Standard]
- `00FFFF` [Aqua / Stack 1]
- `FFFFFF` [White / Stack 2]

As seen in the clip, it **only renders up to aqua**, but the number properly uses white.

**Comment by Tfarcenim** [comment]
should be fixed
