### ISSUE TITLE
Health bar flashing completely White on DMG/REGEN

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#31]
Health bar flashing completely White in the moment of taking damage or regenneing hp instead of just the amount of hp in front of the remaining hp as probably intended! Tested it with just this mod installed as well and default options to make sure of it. And I mean the bar not the boarder all of it border flashes to but that’s intended.

**Comment by Khioni** [comment]
![image](https://user-images.githubusercontent.com/36409872/60273324-e59fa380-98c3-11e9-8d68-9de84d752644.png)
Easy replication, just hug a cactus and watch the bar go completely white.
