### ISSUE TITLE
Hunger Bar Displays Incorrectly w/ Increased Hunger Cap

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/ClassicBar#36]
Minecraft v1.12.2
Forge v14.23.5.2838
Classic Bars v0.3.6
[Random Tweaks](https://www.curseforge.com/minecraft/mc-mods/randomtweaks) v2.7.1.0

Random Tweaks increases the hunger cap, which causes the hunger bar to display incorrectly. 
![2019-08-20_13 09 13](https://user-images.githubusercontent.com/12000593/63448557-c45ebd80-c403-11e9-9ae8-2247e6cbcb1a.png)

**Comment by Tfarcenim** [comment]
yay, another one

**Comment by WenXin20** [comment]
I realized that I have another mod, that I was unaware of, that also uncaps hunger/saturation, [PiTweaks](https://www.curseforge.com/minecraft/mc-mods/cplpibalds-tweaks).

**Comment by WenXin20** [comment]
Unfortunately, I'm still seeing this issue occasionally. I suspect the mod [Nutrition](https://github.com/WesCook/Nutrition) is changing something or that one of the compats isn't working, or maybe I'm wrong about both of those. But something of mine is changing hunger/saturation caps still.
![2019-08-25_23 52 31](https://user-images.githubusercontent.com/12000593/64382180-992abf80-cffa-11e9-8ce2-c3470cc4c406.png)

**Comment by Tfarcenim** [comment]
You'll need to cut out mods then until the culprit is found, you don't have any mods that allow oversaturation do you?

**Comment by WenXin20** [comment]
Does the Nutrition mod allow that? Otherwise I'm not sure yet which mod does.

**Comment by Tfarcenim** [comment]
No, it just allows you to overeat food, but doesn't modify hunger or saturation caps it appears.

**Comment by WenXin20** [comment]
Hmm, I'll have to do some digging then to see if I can find which mod is doing that.

**Comment by Tfarcenim** [comment]
i have killed this for good in 0.5.4
