### ISSUE TITLE
[1.14.4] Crashes on server startup

### ISSUE THREAD

**Issue by al132mc** [Tfarcenim/ClassicBar#38]
Log: [2019-09-10-6.txt](https://github.com/Tfarcenim/ClassicBar/files/3593433/2019-09-10-6.txt)

**Comment by Tfarcenim** [comment]
Why is it on a dedicated server? it's a clientside only mod

**Comment by al132mc** [comment]
If it's clientside only then it should just be inert on a server, no? Otherwise I have to keep a list of which mods to delete every time I update the pack and/or want to copy mods over to the server. If there are only a few mods with non-essential features it's more likely that I just won't include them in my pack in that case when they provide relatively trivial features as it is. On 1.12.2 this mod can be copied over to the server without issue.

**Comment by Tfarcenim** [comment]
as of 1.13, forge made it much more annoying to stop a mod from loading anything on the server as they removed the annotation and still have not provided an alternative.

**Comment by Tfarcenim** [comment]
If you have a better idea, feel free to pr it in, but for now this is looking like a cantfix

**Comment by Tfarcenim** [comment]
forge is being useless as well yay
