### ISSUE TITLE
Suggestion: Vampirism integration

### ISSUE THREAD

**Issue by Curunir** [Tfarcenim/ClassicBar#39]
I like the way this mod just drops into my pack and works for most things. The one exception I noticed so far is Vampirism. That mod converts the hunger/saturation bar into a blood bar, obviously, and right now this looks tolerable even with your mod as it is. But having an actual blood bar in the style of the mod would of course be much preferred.
![classic_bars_vampirism](https://user-images.githubusercontent.com/8467967/64861093-58046200-d62f-11e9-9225-22c74215ec4e.png)

Do note that this is not Witchery vampirism, but the standalone mod by Maxanier.
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire
They have their own Integrations mod, so depending on how easy this is, you may want to reach out and see if Maxanier can help you out:
https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations

Even without this, your mod works fine. Good job.

**Comment by Tfarcenim** [comment]
0.5.2
