### ISSUE TITLE
Crash Upon Boarding A Minecart

### ISSUE THREAD

**Issue by FriendlyGamer** [Tfarcenim/ClassicBar#4]
Literally just board a cart on this mod version 1.1.0 for Minecraft 1.12.2 to obtain instant crash.  
https://hastebin.com/rivoyolope.sql 

Said ClassicBars in it and disabling mod resolved the issue in my mod pack.

**Comment by Tfarcenim** [comment]
It _should_ be fixed on 0.1.2, let me know if you have any issues.

**Comment by FriendlyGamer** [comment]
Thanks! Just in time as I was about to push a hotfix because of Mekanica issues for a downgrade.
