### ISSUE TITLE
Strange animation makes health look like it's going down when it's going up

### ISSUE THREAD

**Issue by esotericist** [Tfarcenim/ClassicBar#40]
I'm not sure how to properly describe it, but there's an animation in the health bar that makes it look like health is going down when it's going up.

In the following gif, my health is ticking up from 15 to 16 due to natural regeneration, but the white section is moving downwards:
![Screen Recording 2019-10-03 at 3 12 50 AM](https://user-images.githubusercontent.com/1569754/66119408-71912d80-e58d-11e9-9931-3c50fdd18df8.gif)

The white section moving downwards catches my attention out of the edge of my vision, giving me the impression of health going down when I'm trying to do other things, which keeps drawing my attention in a negative way.

If there's a way of disabling this animation, I can't figure out how that might be done.

This is with `classicbar-0.4.1.jar`, in Glacial Awakening 1.1.3.

**Comment by esotericist** [comment]
Here's a possibly better gif showing it on a longer span:

![Screen Recording 2019-10-03 at 3 35 55 AM](https://user-images.githubusercontent.com/1569754/66120328-7951d180-e58f-11e9-8fed-4d78e83585d6.gif)

**Comment by Tfarcenim** [comment]
Can you reproduce with a smaller list of mods, it's not happening on my end.

**Comment by esotericist** [comment]
Sorry for the delay, but I still get this in instance isolated to just forge 2847 and classicbar 0.5.2a, no other mods present

Video here:
https://youtu.be/iqMRc1wcFBc
