### ISSUE TITLE
Bug: Rats Mod and Classic bars conflict with plague Debuff.

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#41]
There seems to be a rather annoying issue with the rat’s mod Debuff plague with the classic bars health rendering. It makes plague colored hearts appear behind the hp bar. I am not sure whose problem that would be so I make this post on both ends linking them.
![2019-10-29_23 28 46](https://user-images.githubusercontent.com/39855956/67815465-45db6780-faa7-11e9-871c-3d5f2bec81de.png)
![2019-10-29_23 28 49](https://user-images.githubusercontent.com/39855956/67815466-45db6780-faa7-11e9-8a44-43113b752c2a.png)

https://github.com/Alex-the-666/Rats/issues/111

**Comment by Tfarcenim** [comment]
That looks like a bug on Rats side.

**Comment by Tfarcenim** [comment]
looks like it was fixed on rat's side
