### ISSUE TITLE
Bars rendering incorrectly in various combinations in the new updates worked fine in 0.4.1.

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#42]
There seems to be an issue in classicbar-0.4.2a.jar
That causes some bars to overlap. And some to not render at all!
Here is a picture with all these following bars that should show up.
Decay (btwlands) flight (botania) Lava Charm/Air/Armor/HP/Toughness/Hunger/Absorption
Basically fully buffet in the between lands underwater to show them all at once! It worked fine before the last 2 updates. Also some pics in overworld to show!
Here are some examples:
First the pictures showing all things the wings bar is under all bars for some reason pushing it all up and the absorption bar doesn’t move at all. I have it turned to swap armor and absorption bar so it normally renders the absorption above the armor which makes way more sense anyway since that one can diminish and is mostly never fully drawn out so it looks bad if it’s under the armor.
You can also see how the bars for armor and so overlap with absorption as it doesn’t move. Since when I remove the wings and the bars move down (lava charm does noting no bar at all anywhere but my guess is that its under the air bar and also only triggers when the air bar is up as it looks red under the air when the charm is on.)
![2019-11-22_21 07 45](https://user-images.githubusercontent.com/39855956/69457358-2dd8ca00-0d6d-11ea-871e-503d6bab8ce4.png)
![2019-11-22_21 07 49](https://user-images.githubusercontent.com/39855956/69457362-303b2400-0d6d-11ea-9296-daa82020dc6d.png)
![2019-11-22_21 07 58](https://user-images.githubusercontent.com/39855956/69457546-97f16f00-0d6d-11ea-9876-14559e82f119.png)
![2019-11-22_21 08 01](https://user-images.githubusercontent.com/39855956/69457549-99229c00-0d6d-11ea-8ec6-f27e5f967236.png)
![2019-11-22_21 08 08](https://user-images.githubusercontent.com/39855956/69457553-9b84f600-0d6d-11ea-8d97-b2190a307065.png)
And here now with the armor and absorption swap turned to false (default) the absorption still doesn’t move all bars still move around with wings bar etc
![2019-11-22_21 09 33](https://user-images.githubusercontent.com/39855956/69457706-fc143300-0d6d-11ea-80b6-3705c821bfd3.png)
![2019-11-22_21 09 45](https://user-images.githubusercontent.com/39855956/69457712-fdddf680-0d6d-11ea-8a10-b9c0969e7182.png)
![2019-11-22_21 09 56](https://user-images.githubusercontent.com/39855956/69457715-ffa7ba00-0d6d-11ea-80aa-b0256aa8e094.png)
![2019-11-22_21 10 08](https://user-images.githubusercontent.com/39855956/69457720-01717d80-0d6e-11ea-89ec-a199388c5446.png)

Forge: 14.23.5.2847 
Classic Bars: 0.4.2a
new and fresh generated configs used for testing
modpack: Dimension Zero for testing and modlist is on the curse page for the pack.
and lastly here a pic of it working back in 0.4.1
![2019-11-22_21 37 01](https://user-images.githubusercontent.com/39855956/69458923-d0467c80-0d70-11ea-9b5f-122558d1cf26.png)
And here my configs that I use in 0.4.1 with the armor and absorption swapped to keep armor next the toughness and the increased color palate for armors that goes up to 100 and more. And lastly the changed colors for poison and wither if you need any of that info.
https://pastebin.com/r5ZT4jx2

**Comment by Tfarcenim** [comment]
alright, time for another snapshot, the reason I changed it was so that it was easier to add compat for more mods without hardcoding to hell and back

**Comment by SirAron111** [comment]
OK I did run tests with the new version and it seems that the bars are in order now. Only one problem, Absorption! 2 things the config option to swap absorption and armor gets completely ignored now, absorption stays at the same location all the time if it’s false or true doesn’t matter. Also as soon as you have absorption all bars above even on the other side move one space upwards. Is there no way to have absorption with no config no questions asked simply render on top of all other bars? I mean it’s the only one that never gets fully filled unless you do some crazy commands and this way it won’t move other things around. Armor bar and toughness bar are good when they are next to each other and right above hunger and hp. But well other than absorption bugging around all others seem to be fixed. (tldr absorption is not a static bar but a buff bar should be rendered on top of all others it doesn’t constantly move things up or down when you eat a potion or a golden apple etc)
![2019-11-24_00 30 42](https://user-images.githubusercontent.com/39855956/69486913-e0825880-0e51-11ea-9738-cd674a17a4b2.png)
![2019-11-24_00 30 45](https://user-images.githubusercontent.com/39855956/69486914-e1b38580-0e51-11ea-8091-bb59490596da.png)
![2019-11-24_00 31 43](https://user-images.githubusercontent.com/39855956/69486915-e2e4b280-0e51-11ea-9365-5a3831b03e8a.png)
![2019-11-24_00 31 51](https://user-images.githubusercontent.com/39855956/69486916-e415df80-0e51-11ea-95e1-67ce15c6ac5d.png)
hope that helps

**Comment by SirAron111** [comment]
OK the newest version where you can decide where what bar goes is super nice. I love being able to customize stuff like that. Everything works fine only one thing I still found. Only the Armor bar when you got more armor than the default max of 20 starts to shift out of its bounds a bit her is a picture. If that’s fixed I think it’s perfect. Sry I can only find bugs not help fixing them XD.
![2019-12-01_12 49 02](https://user-images.githubusercontent.com/39855956/69913588-e2dc4800-1439-11ea-8297-5e92b75b9363.png)
![2019-12-01_12 50 45](https://user-images.githubusercontent.com/39855956/69913589-e5d73880-1439-11ea-8f79-a1b8643f00dd.png)
![2019-12-01_12 50 51](https://user-images.githubusercontent.com/39855956/69913590-e66fcf00-1439-11ea-97ce-3342ce562754.png)

**Comment by Tfarcenim** [comment]
0.5.1 should fix this and more issues as well as a further fps boost

**Comment by SirAron111** [comment]
Sry to tell you but that made it somehow worse XD.

Now the armor is fixed but only when you have mixed colored bars. Any one colored bar above the standard value is still one layer up out of bounds. (Here a picture).
![2019-12-01_22 07 31](https://user-images.githubusercontent.com/39855956/69920403-ec8c9c80-1487-11ea-8ae4-3f959b363ee3.png)
![2019-12-01_22 08 07](https://user-images.githubusercontent.com/39855956/69920404-eeeef680-1487-11ea-98ee-bd779afcfe56.png)

And now to the strange part! For some reason as soon as you get the decay bar or have absorption, you get this strange flat colored bar style. I don’t think that’s intentional.
![2019-12-01_22 06 56](https://user-images.githubusercontent.com/39855956/69920406-fca47c00-1487-11ea-9230-970d8a38b506.png)
![2019-12-01_22 07 03](https://user-images.githubusercontent.com/39855956/69920407-fd3d1280-1487-11ea-95b9-b8e5508f3da1.png)
![2019-12-01_22 07 47](https://user-images.githubusercontent.com/39855956/69920408-fd3d1280-1487-11ea-99c5-e70dffe28ae6.png)
![2019-12-01_22 09 04](https://user-images.githubusercontent.com/39855956/69920409-fd3d1280-1487-11ea-9ccf-3dd4a48ce323.png)
![2019-12-01_22 09 17](https://user-images.githubusercontent.com/39855956/69920410-fd3d1280-1487-11ea-9880-6bd1aa753d7f.png)

**Comment by Tfarcenim** [comment]
0.5.1b incoming

**Comment by SirAron111** [comment]
Visually it seems to be working now. But now I get a really strange error spammed to the console here is what it does over and over and over again. And it’s not stopping until you throw away the lava charm or the and take of the flügel tiara as these seem to be the cause for this error message.
https://pastebin.com/rzc8Q3hc
![2019-12-01_23 01 18](https://user-images.githubusercontent.com/39855956/69921042-ee0d9300-148e-11ea-9c01-f1197ff25ec3.png)

**Comment by Tfarcenim** [comment]
fixed in 0.5.1c

**Comment by SirAron111** [comment]
@Tfarcenim Yep the console spam is solved and the visuals all seem to work now.  
![2019-12-02_17 16 46](https://user-images.githubusercontent.com/39855956/69976081-ad625800-1528-11ea-858e-b69510069b5b.png)

And with the possibility of switching the bars around I can finally manage the layout I want loving it. Sry for all the bug posts! Case closed!
![2019-12-02_17 19 34](https://user-images.githubusercontent.com/39855956/69976084-afc4b200-1528-11ea-915e-115285b06353.png)
