### ISSUE TITLE
1.14.4 Install weirdness

### ISSUE THREAD

**Issue by Hexblood** [Tfarcenim/ClassicBar#45]
So I ran into an issue with the mod not being recognized as a valid jar when launching an imported instance through the GDLauncher. When I went over to check things out via the Twitch App I noticed that it says both 2.0.0a and 2.0.0b are installed. On the mod list it says that it is 2.0.0a. The mod loads fine when launching via Twitch.

I am thinking this is an issue on Twitch's end but thought I would let you know. You may be able to get something looked at quicker than I can.

**Comment by Tfarcenim** [comment]
nothing I can do on my end sorry.
