### ISSUE TITLE
Lava Bar always showing

### ISSUE THREAD

**Issue by BillboardEric** [Tfarcenim/ClassicBar#46]
For some reason the Lava bar is always showing even without having the ring or boots
![image](https://user-images.githubusercontent.com/8685981/71773756-11fe4180-2f31-11ea-8f36-6a77a2b2c6aa.png)

Using version 0.5.3

Mod list: https://hastebin.com/lolobijuzu.nginx

**Comment by Velocihater** [comment]
happens to me sometimes too

**Comment by Tfarcenim** [comment]
ded
