### ISSUE TITLE
1.15 issues

### ISSUE THREAD

**Issue by Darkere** [Tfarcenim/ClassicBar#47]
Underwater breath is not showing correctly
![image](https://user-images.githubusercontent.com/4283717/71941487-33be2980-31ba-11ea-91c0-df45632b8346.png)

Holding food flickers too much/fast https://gfycat.com/CorruptMiniatureHuemul
classicbar-3.0.0.jar
forge 30.0.30

**Comment by Tfarcenim** [comment]
is this with no other mods installed?

**Comment by Darkere** [comment]
This is with the [Randomly added mods pack](https://www.curseforge.com/minecraft/modpacks/randomly-added-mods) The bubbles seem to be a conflict with something..

But the rapidly flashing food bar also happens with just classic bars installed.

**Comment by Darkere** [comment]
So I figured out which mod is causing this: https://www.curseforge.com/minecraft/mc-mods/levelhearts

No idea what to tell them other than yelling at them for not documenting their features...
Toughness bar is also from them 
![image](https://user-images.githubusercontent.com/4283717/74570827-4b3cbf00-4f7d-11ea-8385-6be8e760b40e.png)

**Comment by Darkere** [comment]
Looks like the level hearts dev disagrees's with who is at fault. 

`Ah, I see, my apologies I had read your response via email and didn't see your other message. If that's the case, this would be an issue on Overloaded Armor Bar's end. If I recall, another user had a different issue with OAB and we boiled it down to different rendering algorithms, and that OAB needs to add support for LevelHeart's modifier.
I'll look into it more, though, and see if I can't get in touch with Overloaded Armor Bar's developer to see if we can't get this fixed :)`

https://gitlab.com/FireController1847/levelhearts/-/issues/7

**Comment by Tfarcenim** [comment]
if this is about overloaded-armor-bar then why is it in this github, that needs it's own seperate issue.  This is classicbars

**Comment by Darkere** [comment]
I imagine it's the same problem as the one about overloaded-armor-bar. Although I guess I should create an issue about this as well.

**Comment by Darkere** [comment]
Sigh. At some point, they've sneakily added in a config that disables their GUI changes. (Or I'm dumb and missed them somehow...)

Anyway sorry for being obnoxious <3
