### ISSUE TITLE
When Dark Theme Mod installed, 2 black lines appear in all of the bars

### ISSUE THREAD

**Issue by BugmanBugman** [Tfarcenim/ClassicBar#48]
![image](https://user-images.githubusercontent.com/40730042/72214118-9b79ba80-34c1-11ea-9240-748d5d56913e.png)
Here is the [link to the mod](https://www.curseforge.com/minecraft/mc-mods/dark-theme-mod). I think this occurs since Dark Theme Mod doesn't support Classic Bars.

**Comment by Tfarcenim** [comment]
that's a bug in their mod, not mine.
