### ISSUE TITLE
Terrafirmacraft compatibility.

### ISSUE THREAD

**Issue by KokSaker** [Tfarcenim/ClassicBar#49]
The bar from this mod  underlays the terrafirmacraft-TNG(the 1.12.2 version) default bars. If possible, maybe you could override the default TFC bars.

**Comment by Tfarcenim** [comment]
try asking them for a config to switch it off, I don't like to hack into other mod's code unless I absolutely have to

**Comment by KokSaker** [comment]
There is such an option in TFC TNG to show the default bar but there is not thirst bar in classic bars mod.
