### ISSUE TITLE
A few Suggestions and quality of live ideas!

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#5]
First would be making sure that the absorption appears over the armor bar and not moves it upwards. It looks wired having a tiny bit of absorption under the big armor bare and watching the armor bar move up and down when you have a absorption that regenerates is annoying.

Second would be being able to slightly adjust the width and heights of the bars to make them a bit smaller for people who prefer them visible but not super big as not everyone uses the big Minecraft UI.

Adding in compatibility for the exhaustion overlay added by apple skin (the one that normally looks like a background checkerboard pattern just doesn’t go well with the bars but having an indicator how much exhaustion you get per second would still be nice so removing it would be not so good)

And the last one for now would be a really important one. Adding in some kind of indicator for effects that normally color the bars like poison, wither, hunger etc. (maybe you could add in a small outer layer that gets like a effect or small animation like a bubbly purple framing around the health bar for poison or a black tar like one for wither, and something for the hunger bar as well) as simply having no such indicator seems a bit lacking.

Here are some pictures of what I mean.

First the Armor bar moving up looking bad with the tiny absorption under it instead of over it and the checkerboard exhaustion overlay.
![2019-03-28_17 24 46](https://user-images.githubusercontent.com/39855956/55176557-a0af8800-5181-11e9-8677-8412d8b2a224.png)

And here me having effects like hunger poison and wither but the bars stay the same (simply having them change color would be ok to but adding a kind of border thing like I mentioned would enhance the visual allot)
![2019-03-28_17 25 47](https://user-images.githubusercontent.com/39855956/55176574-a86f2c80-5181-11e9-9ae1-0c7287e530b1.png)

**Comment by Tfarcenim** [comment]
One thing at a time
> First would be making sure that the absorption appears over the armor bar and not moves it upwards.
Will see about adding a swap config

> Second would be being able to slightly adjust the width and heights of the bars to make them a bit smaller for people who prefer them visible

Width is easy enough to do, but as for height, that will be tricky to do and not look like trash as well as scaling the text.

>Adding in compatibility for the exhaustion overlay added by apple skin (the one that normally looks like a background checkerboard pattern just doesn’t go well with the bars but having an indicator how much exhaustion you get per second would still be nice

The overlay itself can be disabled although I am leery of adding any more numbers to the screen

>Adding in some kind of indicator for effects that normally color the bars like poison, wither, hunger etc. (maybe you could add in a small outer layer that gets like a effect or small animation like a bubbly purple framing around the health bar for poison or a black tar like one for wither, and something for the hunger bar as well) as simply having no such indicator seems a bit lacking.

The framework for the icons is already set and as for the bar itself, it's a matter of a simple recolor.

I will get to as many of these as I can.

**Comment by SirAron111** [comment]
Thx for considering these ideas.

As for the borders even just having them flash up in a debuff related color would be an idea if the others don’t work visual is always better than numbers. (Thought an option to have the numbers inside the bars would be a nice choice for people who like it compact)

**Comment by SirAron111** [comment]
If this is a bother just tell me. If not I will keep adding to the list a few things if I find something that could make use of the potential this mod has wile testing around with it.

Another thing that I found a bit wired looking is the health bars with being of fire. The big fire effect that normal minecraft has blocking most part of the screen makes the health bars look a bit overshadowed as they are mostly flat colored. Is it possible to block the flame effect that is on the player when being on fire and instead have the health bar burn (have a little flame effect overlaid). Actually by just having another overlay that is attached to each bar would resolve the issue on how to properly display other effects as well so for example when player is poisoned you get overlaid a little poison bubbling ,semi transparent so you can still see the normal bar, effect instead of the boarder I mentioned before. This would also make the whole thing more compact by keeping the effects in the bars.

Here is an example I made with paint XD think of the effects as an overlay that is rendered above the bar when the effect is in action. And maybe animated. Thought the poison one didn’t turn out that good.

![Bars_Test_Fire](https://user-images.githubusercontent.com/39855956/55241474-6c989d80-523b-11e9-95d9-38a2cea439e2.png)
![Bars_Test](https://user-images.githubusercontent.com/39855956/55241479-6e626100-523b-11e9-9b82-3fcb2bae8e08.png)

**Comment by Tfarcenim** [comment]
Adding effects to the bars is easy, removing the vanilla fire overlay, not so much.

**Comment by SirAron111** [comment]
Suggestion:
Botania Flügel Tiara Flight Indicator bar integration.
Is it possible to have a small bar that indicates flight from the Botania mod? Atm the Bars just overlap. With the little wing indicators.
XD. So many bars you should consider making them all a tiny bit smaller at some point or the screen will get overcrowded.

Also I decided to implement this mod in the next update of my pack. Loving it so far.

**Comment by SirAron111** [comment]
Well found a simple trick to fix the botania wing bar (simply set in the config of botania the wing bar height of 49/59 to 59/69) first number is without breath bar second is with breath bar.
There is an option for that you should make that as a little disclaimer or have your mod auto set the bar to these values so it’s not overlapping. Loving the mod great work
Hope that some kind of neat visual effects will come to the bars in the future, like in my pictures above if not it’s also not a problem its already great as it is I am just a fan of visuals and effects XD

**Comment by Tfarcenim** [comment]
I was able to add the bar for the wings but I am having extreme difficulty removing it.

**Comment by Tfarcenim** [comment]
nvm, was easier than i thought, just have to mess with botania config to hide the bar.

**Comment by Tfarcenim** [comment]
seems like all of them have been resolved
