### ISSUE TITLE
Incompatibility with Metamorph's squid morph when out of water

### ISSUE THREAD

**Issue by James103** [Tfarcenim/ClassicBar#53]
Minecraft 1.12.2
Forge 14.23.5.2847
Metamorph 1.1.10-1.12.2 (or Changeling equivalent)
Classic Bar 0.5.4
See mchorse/metamorph#208

When morphed as a Squid and out of water, the air meter displayed is the **Minecraft default** and not the one from Classic Bar, which is inconsistent.

To Reproduce:
1. Install the aforementioned mods.
2. Be underwater. Notice the air meter displayed is the one from Classic Bar.
3. Morph to a Squid. Notice the air meter disappears as it should (you can only breathe underwater).
4. Jump out of water. Notice the air meter displayed is the **Minecraft default** and not the one from Classic Bar.

**Comment by Tfarcenim** [comment]
That appears to be caused by them rendering their own copy of the air bar instead of letting vanilla handle it, nothing I can do about it on my end

**Comment by asanetargoss** [comment]
Tfarcenim's right, their hands are a bit tied here.

I initially considered implementing the squid air bar by overriding the player's air stat, but worried that may cause unintended side-effects. However, that may be worth re-visiting. Very low priority for me, though.
