### ISSUE TITLE
Hunger/saturation bar not always scaling to cap when cap is increased by Scaling Feast

### ISSUE THREAD

**Issue by Sardav** [Tfarcenim/ClassicBar#55]
Playing on Minecraft 1.12.2 with Forge 14.23.5.2852, ClassicBar 0.5.4, ScalingFeast 1.2.6-beta, among other mods.

Expected behaviour: the hunger and saturation bar, when the cap for said attributes is extended past the vanilla 20 by Scaling Feast, should encompass the whole new cap. For example if the cap is 30 and the current hunger is 20, it should be filled only 2/3rds. The health bar already displays this behaviour when extended by, for example, Spice Of Life Carrot Edition.

Observed behaviour: the hunger and saturation bar, when the cap is over 20 and the current value is 20 or less, displays the bars scaled to a cap of 20. When the hunger value is raised above 20 by eating, the entire bar is then scaled to the *current* value (this can be observed because the yellow saturation overlay is also scaled to this value, resulting in slightly smaller-than-expected yellow bar after eating). This results in an inaccurate reading of hunger and saturation relative to the cap, and an inconsistent behaviour when compared to the extended health bar.

In the image attached, both health and hunger/saturation caps have been extended to 32 by using Spice Of Life Carrot Edition and Scaling Feast, respectively. It can be observed that the health bar scales properly while the hunger bar is only adjusted to the current non-full value of 27. 

![unknown](https://user-images.githubusercontent.com/64608585/80750477-88d1d280-8afe-11ea-88e1-c0a87385f5db.png)

**Comment by Tfarcenim** [comment]
sigh, this is the 5th mod that feels the need to change the hunger bar...

**Comment by James103** [comment]
When I tried it myself, **two** hunger bars were displayed: the one from Classic Bar and the one from Scaling Feast. Expected: Only the hunger bar from Classic Bar is displayed when enabled, with proper scaling. Scaling Feast 1.3.1 and Classic Bar 0.5.4 (both from curseforge) are the two mods used.

**Comment by RayDurand** [comment]
> 
> 
> When I tried it myself, **two** hunger bars were displayed: the one from Classic Bar and the one from Scaling Feast. Expected: Only the hunger bar from Classic Bar is displayed when enabled, with proper scaling. Scaling Feast 1.3.1 and Classic Bar 0.5.4 (both from curseforge) are the two mods used.

Scaling Feast comes with two HUD modes, "Overlay" and "Default". Overlay causes an additional hunger bar to appear, but setting it to Default in the mod options makes only the Classic Bar one visible.

**Comment by James103** [comment]
I think this behavior is caused by the fix to #28, #32, and/or #36. Basically the logic is this:
"Display the hunger bar scaled to a max of your current food level or 20, whichever is higher".
Instead, it should be this:
1. Check that the tag `ForgeCaps.scalingfeast:foodcap` exists in the current player's data.
2. If so, display the hunger bar scaled to a max of the value found in the above tag.
3. If not, display the hunger bar scaled to a max of your current food level (or 20, whichever is higher).
