### ISSUE TITLE
[1.15.2] Mod Compability: Thirst Bar from mod "Survive" not visible

### ISSUE THREAD

**Issue by realTIMematrix** [Tfarcenim/ClassicBar#59]
Hi,

is it possible to add the thirst bar from the mod [survive](https://www.curseforge.com/minecraft/mc-mods/survive)?

thank you

**Comment by Tfarcenim** [comment]
due to the In the interest of time, I am only accepting feature requests for the latest version of mc, as of this writing that is 1.16.1, and survive is not on 1.16 yet.  Notify me when it's updated and I'll add it.
