### ISSUE TITLE
Toughness Bar Bug

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#6]
Toughness bar is gone now. New update classicbar-0.1.4 stopped toughness bar from rendering at all. Even with its config turned on or off both tested after restart.

![2019-03-29_21 06 18](https://user-images.githubusercontent.com/39855956/55259790-f01bb400-5266-11e9-8246-92cfcb4abd48.png)

**Comment by Tfarcenim** [comment]
bug will be fixed in 0.1.5, sorry about that

**Comment by SirAron111** [comment]
Np XD I always find all the bugs in existence when I test and tweak around my Modpack. For example I found a bug once that only happens when you stand on a IMCraft rock lock down a ladder/vine and try to hit something. Causing a certain mod (not IMCraft) to break and crash the game XD.

I think of it as trying to help myself improve my pack and keeping it bug free as well as helping the mod makers find bugs they normally cant test unless they test it together with other mods (love finding conflicts). So the one who should apologies is me since if I find interest in a mod I can be pretty persistent Xp
