### ISSUE TITLE
[1.14.4] Curseforge appears to have the wrong file

### ISSUE THREAD

**Issue by FastBoye127** [Tfarcenim/ClassicBar#60]
Curseforge delivers 2.0.0a instead of 2.0.0b. Screenshot attached.

![Annotation 2020-05-24 103807](https://user-images.githubusercontent.com/35196473/82758197-b1ba5000-9daa-11ea-808d-fe1746e29027.png)

**Comment by Tfarcenim** [comment]
bad naming, nothing I can do now
