### ISSUE TITLE
[1.16.1] Mod Compability: Thirst Bar from mod "Survive" not visible 

### ISSUE THREAD

**Issue by realTIMematrix** [Tfarcenim/ClassicBar#61]
Hi,

Survive Mod is now ported to 1.16.1. Is it possible to add the thirst bar?

https://www.curseforge.com/minecraft/mc-mods/survive

best regards

**Comment by Tfarcenim** [comment]
mod seems to be closed source, nothing I can do
 https://github.com/Stereowalker/Survive/

**Comment by Kevadroz** [comment]
Seems like the source code was uploaded on december, ¿what about now?
