### ISSUE TITLE
[Request] 1.16.3 update

### ISSUE THREAD

**Issue by 3x1at1on** [Tfarcenim/ClassicBar#63]
Love your mod which makes the UI better. Can you update it to 1.16.3 please?

**Comment by daiaji** [comment]
I tried to modify the mods.toml file in the mod, but it didn’t seem to be of any use...

**Comment by 3x1at1on** [comment]
Easy to sort out by the way.
Just needed to add the license="MIT" to the mods.toml file and bump up the resources pack format version to 6 in pack.mcmeta

**Comment by Tfarcenim** [comment]
https://www.curseforge.com/minecraft/mc-mods/classic-bars/files/3098254
