### ISSUE TITLE
Vampirism Compatibility

### ISSUE THREAD

**Issue by maxanier** [Tfarcenim/ClassicBar#65]
I was made aware that the ClassicBar mod adds integrations for Vampirism which I very much appreciate. Unfortunately, the Vampirism blood bar is sometimes rendered instead of the ClassicBar's version. In my quick test it was working as intended, but I have heard contrary statements

Likely Vampirism catches the `RenderGameOverlayEvent.Pre#FOOD` event before ClassicBar and cancels it. Both mods subscribe on normal priority and it appears it is not guaranteed which mod receives the event first.

So one solution could be to change your subscription priority to HIGH, so you can cancel the event before Vampirism receives it. However, this could introduce issues with other mods that replace GUI elements as ClassicBar will always win.

An alternative solution would be to request Vampirism to not render the bar. I have recently added a IMC message to allow this without any code/API dependency:
Just send `disable-blood-bar` to `vampirism` during `InterModEnqueueEvent`.
(Was added to Vampirism 1.7-beta.3 for 1.15 but will make its way to 1.16 as well)

**Comment by Tfarcenim** [comment]
Shouldn't be an issue in 4.1.1
