### ISSUE TITLE
health numbers disappear when hearts are in the yellow

### ISSUE THREAD

**Issue by BugmanBugman** [Tfarcenim/ClassicBar#66]
![2020-11-27_22 43 09](https://user-images.githubusercontent.com/40730042/100494099-e0233a00-3103-11eb-86b4-774b278f190c.png)
![2020-11-27_22 40 19](https://user-images.githubusercontent.com/40730042/100494106-ec0efc00-3103-11eb-9a1b-4eab5d9d543e.png)

**Comment by Tfarcenim** [comment]
Can't recreate
