### ISSUE TITLE
ClassicBar causes crash with Betweenlands

### ISSUE THREAD

**Issue by 3216100** [Tfarcenim/ClassicBar#7]
The game crashes when right clicking a [Weedwood Rowboat](https://the-betweenlands.fandom.com/wiki/Weedwood_Rowboat) in the Betweenlands, and the crash report ([available here](https://pastebin.com/BZH14mLY), relevant code begins on line 31) attributes it to ClassicBar.

Here is the crash description from the launcher:
> The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: thebetweenlands.client.handler.WeedwoodRowboatHandler$RowboatCam cannot be cast to net.minecraft.entity.player.EntityPlayer

The error stems from the boat using a custom entity for the camera position, and was discovered in 2017 as a result of ArsMagica2, reported [here](https://github.com/Angry-Pixel/The-Betweenlands/issues/387), [here](https://github.com/Mithion/ArsMagica2/issues/1608) and [here](https://github.com/Growlith1223/ArsMagica2/issues/304). I'm reporting it to this repository because the Betweenlands devs suggested the same be done in the previous case; nothing can be done on their side.

Edit: I'm running the All the Mods 3 - Redux modpack, which just added ClassicBar in its 1.2.1 update. (mod looks great by the way)

**Comment by Tfarcenim** [comment]
This was fixed in 0.1.3+, update to at least that.

**Comment by 3216100** [comment]
Thanks! Good to know
