### ISSUE TITLE
[1.16.5] ToughAsNails Incompatibility

### ISSUE THREAD

**Issue by Jerdn** [Tfarcenim/ClassicBar#76]
ToughAsNails not having a bar appearance in ver. 1.16.5

![2021-03-31_07 03 46](https://user-images.githubusercontent.com/81695883/113156923-48d40d80-91ef-11eb-8b9c-6d0a9d06bb79.png)

**Comment by Tfarcenim** [comment]
intended, they brought it on themselves
![image](https://user-images.githubusercontent.com/44327798/113159499-a590f180-920a-11eb-84c8-6008117edd20.png)
