### ISSUE TITLE
Weird UI bug with Water Source

### ISSUE THREAD

**Issue by vizthex123** [Tfarcenim/ClassicBar#81]
I've noticed that the inventory UI looks like this when both mods are enabled:

![image](https://user-images.githubusercontent.com/31721920/126886237-55851129-cb04-44ab-bf1b-4bbe598e529d.png)

But when either mod is disabled, it works fine.

Could this get fixed?

I've also [reported it to the Water Source author.](https://github.com/lemon-slice-studio/WaterSource/issues/26)

Game log:
[latest.log](https://github.com/Tfarcenim/ClassicBar/files/6873311/latest.log)

**Comment by Tfarcenim** [comment]
I don't think this is my fault.
