### ISSUE TITLE
Could you add support for SimpleDifficulty in the 1.12.2 version?

### ISSUE THREAD

**Issue by vizthex123** [Tfarcenim/ClassicBar#82]
Title. Tough As Nails doesn't work anymore, but I found that this mod also adds a thirst bar, but it's not supported by Classic Bar.

**Comment by Tfarcenim** [comment]
No, feature additions to versions lower than 1.17.1 are no longer in consideration.

**Comment by vizthex123** [comment]
Damn, that sucks.... this has always been one of my favourite 1.12.2 mods.
