### ISSUE TITLE
Crash upon death with Vampirism

### ISSUE THREAD

**Issue by maxanier** [Tfarcenim/ClassicBar#83]
When running up-to-date versions of Vampirism and ClassicBar and dying as a vampire the game crashes.
Crashreport: 
[crash-2021-08-19_21.27.44-client.txt](https://github.com/Tfarcenim/ClassicBar/files/7020946/crash-2021-08-19_21.27.44-client.txt)
forge-1.16.5-36.2.2-client.jar
Vampirism-1.16.5-1.8.0-beta.5.jar 
classicbar-4.1.0-1.16.5.jar

This is caused by the fact that capabilities are not available for dead entities. Therefore https://github.com/Tfarcenim/ClassicBar/blob/51eecb1ab17c3d7e688d343f85889ba007ad52f9/src/main/java/tfar/classicbar/overlays/mod/Blood.java#L40 fails.
I assume in previous Vampirism versions https://github.com/Tfarcenim/ClassicBar/blob/51eecb1ab17c3d7e688d343f85889ba007ad52f9/src/main/java/tfar/classicbar/overlays/mod/Blood.java#L35 returned false when the player is dead and therefore avoided this issue. 
To avoid this issue please check if the player `isAlive()` before doing `VampirePlayer#get` or better use `VampirePlayer#getOpt` to get a safe `LazyOptional`.
It might also be a good idea to migrate to Vampirism's API only entirely.

**Comment by maxanier** [comment]
I could do a PR (in a couple of weeks only though) and also consider #65, if you would like that.

**Comment by Tfarcenim** [comment]
This will be fixed in 4.1.1
