### ISSUE TITLE
elenai dodge 2 compat crash

### ISSUE THREAD

**Issue by Wedge1453** [Tfarcenim/ClassicBar#85]
created world in creative, crashed when I switched to survival.
[crash-2021-09-15_12.23.20-client.txt](https://github.com/Tfarcenim/ClassicBar/files/7169605/crash-2021-09-15_12.23.20-client.txt)

**Comment by Shibva** [comment]
this issue has something done in a pull request, it has yet to be merged, for months now

**Comment by Tfarcenim** [comment]
4.1.1 will have it
