### ISSUE TITLE
1.16.5 - 4.1.0 - forge 36.2.0 - empty bars at 6 food/health

### ISSUE THREAD

**Issue by audenga** [Tfarcenim/ClassicBar#87]
when hunger or health hits 6 or bellow the bar just shows as empty, tried with and without optifine
https://imgur.com/a/qLamH2c

**Comment by Shibva** [comment]
can confirm, but you might wanna give more info than that, whats your mod count and what mods are present?

**Comment by Tfarcenim** [comment]
Confirmed, fixed in 4.1.1

**Comment by Shibva** [comment]
Thank you
