### ISSUE TITLE
[1.12.2] Absorption Bar Overflow.

### ISSUE THREAD

**Issue by Z-Tunic** [Tfarcenim/ClassicBar#9]
![](https://cdn.discordapp.com/attachments/377171551155650560/562285626414596116/classicbarabsorbbaroverflow.PNG)

Having high Absorption Levels causes this to happen. You can get this kind of absorption if you use the Natural Absorption mod or if you get a powerful Potion Effect. I think Botania's Mana in a Bottle can give up to 40 Absorption... if lucky.

**Comment by Tfarcenim** [comment]
Absorption above max health? Wot in tarnation...

**Comment by Tfarcenim** [comment]
fixed in 0.1.7
