### ISSUE TITLE
Plague overlay from rats Clashes with Classic Bars

### ISSUE THREAD

**Issue by mistaboom** [Tfarcenim/ClassicBar#90]
Minecraft Version 1.12.2

To reproduce, install:
Rats,
Classic Bars,
and any hp increasing mod. Level Up HP, Spice of live, etc.
Then get plagued by Rats.

You will see many plagued hearts displayed over Classic Bars bars.

You can of course disable the Rats Plague overlay in the rats config but it would be nicer to have the health bar overlay plague or outline green when plagued or something.

**Comment by Tfarcenim** [comment]
not my problem
